GET http://localhost:3333
###

GET http://localhost:3333/api/movies
###
GET http://localhost:3333/api/movies/3
###

POST http://localhost:3333/api/movies HTTP/1.1
content-type: application/json
{
    "title": "Star Wars"
}